# Generated by Django 4.1.7 on 2023-03-10 02:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('content', models.TextField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notetaking.tag')),
            ],
        ),
    ]
